// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// archive_extract.cpp
void archive_extract_(const std::string& archive_filename, cpp11::strings filenames, cpp11::strings options, size_t sz);
extern "C" SEXP _archive_archive_extract_(SEXP archive_filename, SEXP filenames, SEXP options, SEXP sz) {
  BEGIN_CPP11
    archive_extract_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(archive_filename), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(filenames), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options), cpp11::as_cpp<cpp11::decay_t<size_t>>(sz));
    return R_NilValue;
  END_CPP11
}
// archive_read.cpp
SEXP archive_read_(const std::string& archive_filename, const std::string& filename, const std::string& mode, cpp11::integers format, cpp11::integers filters, cpp11::strings options, size_t sz);
extern "C" SEXP _archive_archive_read_(SEXP archive_filename, SEXP filename, SEXP mode, SEXP format, SEXP filters, SEXP options, SEXP sz) {
  BEGIN_CPP11
    return cpp11::as_sexp(archive_read_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(archive_filename), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(filename), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(mode), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(format), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(filters), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options), cpp11::as_cpp<cpp11::decay_t<size_t>>(sz)));
  END_CPP11
}
// archive_write_direct.cpp
SEXP archive_write_direct_(const std::string& archive_filename, const std::string& filename, std::string mode, int format, cpp11::integers filters, cpp11::strings options, size_t sz);
extern "C" SEXP _archive_archive_write_direct_(SEXP archive_filename, SEXP filename, SEXP mode, SEXP format, SEXP filters, SEXP options, SEXP sz) {
  BEGIN_CPP11
    return cpp11::as_sexp(archive_write_direct_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(archive_filename), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(filename), cpp11::as_cpp<cpp11::decay_t<std::string>>(mode), cpp11::as_cpp<cpp11::decay_t<int>>(format), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(filters), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options), cpp11::as_cpp<cpp11::decay_t<size_t>>(sz)));
  END_CPP11
}
// archive_write_files.cpp
SEXP archive_write_files_(const std::string& archive_filename, cpp11::strings files, int format, cpp11::integers filters, cpp11::strings options, size_t sz);
extern "C" SEXP _archive_archive_write_files_(SEXP archive_filename, SEXP files, SEXP format, SEXP filters, SEXP options, SEXP sz) {
  BEGIN_CPP11
    return cpp11::as_sexp(archive_write_files_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(archive_filename), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(files), cpp11::as_cpp<cpp11::decay_t<int>>(format), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(filters), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options), cpp11::as_cpp<cpp11::decay_t<size_t>>(sz)));
  END_CPP11
}
// archive_write.cpp
SEXP archive_write_(const std::string& archive_filename, const std::string& filename, const std::string& mode, int format, cpp11::integers filters, cpp11::strings options, size_t sz);
extern "C" SEXP _archive_archive_write_(SEXP archive_filename, SEXP filename, SEXP mode, SEXP format, SEXP filters, SEXP options, SEXP sz) {
  BEGIN_CPP11
    return cpp11::as_sexp(archive_write_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(archive_filename), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(filename), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(mode), cpp11::as_cpp<cpp11::decay_t<int>>(format), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(filters), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options), cpp11::as_cpp<cpp11::decay_t<size_t>>(sz)));
  END_CPP11
}
// archive.cpp
cpp11::sexp archive_(const std::string& path, cpp11::strings options);
extern "C" SEXP _archive_archive_(SEXP path, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(archive_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(path), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options)));
  END_CPP11
}
// archive.cpp
cpp11::integers archive_filters();
extern "C" SEXP _archive_archive_filters() {
  BEGIN_CPP11
    return cpp11::as_sexp(archive_filters());
  END_CPP11
}
// archive.cpp
cpp11::integers archive_formats();
extern "C" SEXP _archive_archive_formats() {
  BEGIN_CPP11
    return cpp11::as_sexp(archive_formats());
  END_CPP11
}
// archive.cpp
std::string libarchive_version_();
extern "C" SEXP _archive_libarchive_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(libarchive_version_());
  END_CPP11
}
// archive.cpp
const char* libarchive_zlib_version_();
extern "C" SEXP _archive_libarchive_zlib_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(libarchive_zlib_version_());
  END_CPP11
}
// archive.cpp
const char* libarchive_liblzma_version_();
extern "C" SEXP _archive_libarchive_liblzma_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(libarchive_liblzma_version_());
  END_CPP11
}
// archive.cpp
const char* libarchive_bzlib_version_();
extern "C" SEXP _archive_libarchive_bzlib_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(libarchive_bzlib_version_());
  END_CPP11
}
// archive.cpp
const char* libarchive_liblz4_version_();
extern "C" SEXP _archive_libarchive_liblz4_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(libarchive_liblz4_version_());
  END_CPP11
}
// archive.cpp
const char* libarchive_libzstd_version();
extern "C" SEXP _archive_libarchive_libzstd_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(libarchive_libzstd_version());
  END_CPP11
}
// file_write.cpp
SEXP file_write_(const std::string& filename, cpp11::integers filters, cpp11::strings options);
extern "C" SEXP _archive_file_write_(SEXP filename, SEXP filters, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(file_write_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(filename), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(filters), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options)));
  END_CPP11
}
// r_archive.h
void rchive_init(SEXP xptr);
extern "C" SEXP _archive_rchive_init(SEXP xptr) {
  BEGIN_CPP11
    rchive_init(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xptr));
    return R_NilValue;
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _archive_archive_(SEXP, SEXP);
extern SEXP _archive_archive_extract_(SEXP, SEXP, SEXP, SEXP);
extern SEXP _archive_archive_filters();
extern SEXP _archive_archive_formats();
extern SEXP _archive_archive_read_(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _archive_archive_write_(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _archive_archive_write_direct_(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _archive_archive_write_files_(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _archive_file_write_(SEXP, SEXP, SEXP);
extern SEXP _archive_libarchive_bzlib_version_();
extern SEXP _archive_libarchive_liblz4_version_();
extern SEXP _archive_libarchive_liblzma_version_();
extern SEXP _archive_libarchive_libzstd_version();
extern SEXP _archive_libarchive_version_();
extern SEXP _archive_libarchive_zlib_version_();
extern SEXP _archive_rchive_init(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_archive_archive_",                    (DL_FUNC) &_archive_archive_,                    2},
    {"_archive_archive_extract_",            (DL_FUNC) &_archive_archive_extract_,            4},
    {"_archive_archive_filters",             (DL_FUNC) &_archive_archive_filters,             0},
    {"_archive_archive_formats",             (DL_FUNC) &_archive_archive_formats,             0},
    {"_archive_archive_read_",               (DL_FUNC) &_archive_archive_read_,               7},
    {"_archive_archive_write_",              (DL_FUNC) &_archive_archive_write_,              7},
    {"_archive_archive_write_direct_",       (DL_FUNC) &_archive_archive_write_direct_,       7},
    {"_archive_archive_write_files_",        (DL_FUNC) &_archive_archive_write_files_,        6},
    {"_archive_file_write_",                 (DL_FUNC) &_archive_file_write_,                 3},
    {"_archive_libarchive_bzlib_version_",   (DL_FUNC) &_archive_libarchive_bzlib_version_,   0},
    {"_archive_libarchive_liblz4_version_",  (DL_FUNC) &_archive_libarchive_liblz4_version_,  0},
    {"_archive_libarchive_liblzma_version_", (DL_FUNC) &_archive_libarchive_liblzma_version_, 0},
    {"_archive_libarchive_libzstd_version",  (DL_FUNC) &_archive_libarchive_libzstd_version,  0},
    {"_archive_libarchive_version_",         (DL_FUNC) &_archive_libarchive_version_,         0},
    {"_archive_libarchive_zlib_version_",    (DL_FUNC) &_archive_libarchive_zlib_version_,    0},
    {"_archive_rchive_init",                 (DL_FUNC) &_archive_rchive_init,                 1},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_archive(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
