# Generated by cpp11: do not edit by hand

archive_extract_ <- function(archive_filename, filenames, options, sz) {
  invisible(.Call(`_archive_archive_extract_`, archive_filename, filenames, options, sz))
}

archive_read_ <- function(archive_filename, filename, mode, format, filters, options, sz) {
  .Call(`_archive_archive_read_`, archive_filename, filename, mode, format, filters, options, sz)
}

archive_write_files_ <- function(archive_filename, files, format, filters, options, sz) {
  .Call(`_archive_archive_write_files_`, archive_filename, files, format, filters, options, sz)
}

archive_write_ <- function(archive_filename, filename, format, filters, options, sz) {
  .Call(`_archive_archive_write_`, archive_filename, filename, format, filters, options, sz)
}

archive_ <- function(path, options) {
  .Call(`_archive_archive_`, path, options)
}

archive_filters <- function() {
  .Call(`_archive_archive_filters`)
}

archive_formats <- function() {
  .Call(`_archive_archive_formats`)
}

libarchive_version_ <- function() {
  .Call(`_archive_libarchive_version_`)
}

file_read_ <- function(filename, mode, sz) {
  .Call(`_archive_file_read_`, filename, mode, sz)
}

file_write_ <- function(filename, filters, options) {
  .Call(`_archive_file_write_`, filename, filters, options)
}

rchive_init <- function(xptr) {
  invisible(.Call(`_archive_rchive_init`, xptr))
}
