# Generated by cpp11: do not edit by hand

archive_metadata <- function(path) {
  .Call(`_archive_archive_metadata`, path)
}

archive_filters <- function() {
  .Call(`_archive_archive_filters`)
}

archive_formats <- function() {
  .Call(`_archive_archive_formats`)
}

libarchive_version_ <- function() {
  .Call(`_archive_libarchive_version_`)
}

archive_extract_ <- function(archive_filename, filenames, sz) {
  invisible(.Call(`_archive_archive_extract_`, archive_filename, filenames, sz))
}

rchive_init <- function(xptr) {
  invisible(.Call(`_archive_rchive_init`, xptr))
}

read_file_connection <- function(filename, mode, sz) {
  .Call(`_archive_read_file_connection`, filename, mode, sz)
}

read_connection <- function(archive_filename, filename, mode, format, filters, sz) {
  .Call(`_archive_read_connection`, archive_filename, filename, mode, format, filters, sz)
}

write_file_connection <- function(filename, filters) {
  .Call(`_archive_write_file_connection`, filename, filters)
}

write_files_ <- function(archive_filename, files, format, filters, sz) {
  .Call(`_archive_write_files_`, archive_filename, files, format, filters, sz)
}

write_connection <- function(archive_filename, filename, format, filters, sz) {
  .Call(`_archive_write_connection`, archive_filename, filename, format, filters, sz)
}
