# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

archive_metadata <- function(path) {
    .Call('archive_archive_metadata', PACKAGE = 'archive', path)
}

read_connection <- function(archive_filename, filename, sz = 16384L) {
    .Call('archive_read_connection', PACKAGE = 'archive', archive_filename, filename, sz)
}

write_connection <- function(archive_filename, filename, sz = 16384L) {
    .Call('archive_write_connection', PACKAGE = 'archive', archive_filename, filename, sz)
}

write_files <- function(archive_filename, files, sz = 16384L) {
    .Call('archive_write_files', PACKAGE = 'archive', archive_filename, files, sz)
}

